### ISSUE TITLE
poor documentation

### ISSUE THREAD

**Issue by askdesigners** [roughcoder/grunt-humans-txt#1]
The docs are really not sufficient to know what this does or how to do it. "do something with whatever" is very unclear, and perhaps even borderline trolling.

**Comment by roughcoder** [comment]
Soz @askdesigners this was not really a public project or the latest code, made a quick plugin to help with a project... The readme was pretty much the default boilerplate for a grunt plugin - sorry you have issues actually reading code to see how it works.
